# Generated by Django 5.2.7 on 2025-10-27 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='author',
        ),
    ]
