# Generated by Django 5.2.7 on 2025-10-28 06:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_like_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='post_id',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('author', 'post_id')},
        ),
    ]
