# Generated by Django 5.2.7 on 2025-11-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0006_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="views",
            field=models.IntegerField(max_length=11, null=True),
        ),
    ]
